# -*- coding: utf-8 -*-
"""
MercaFlow Comparison v2 — PicSet's exact prompt, 8 images, all 10 products
PicSet analysis (free) vs Our Gemini Flash (same prompt) → both generate with Gemini Pro
"""
import sys, io, json, requests, time, os
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
import oss2
from google.genai import types
from vertex_client import get_client, PLANNING_MODEL, GENERATION_MODEL
from evaluator import score_image
from product_analyzer import analyze_product, FALLBACK_REQUIREMENTS

# === KEYS ===
ANON_KEY = os.environ.get('PICSET_ANON_KEY', '')

with open('evals/picset-token.json', encoding='utf-8') as f:
    ACCESS_TOKEN = json.loads(f.read())['access_token']

BASE = 'https://picsetai.cn/supabase'
USER_ID = 'bd1ec1fc-56b6-4656-b70d-a7c163fa2895'
gemini = get_client()
NUM_IMAGES = 8
# REQUIREMENTS is now per-product, generated by Step 0 (product_analyzer.analyze_product)
# We keep FALLBACK_REQUIREMENTS as the safety net for picset_analyze (which we still want
# to compare apples-to-apples — they only see the same one-liner we used to send)

# Load PicSet's exact prompt template
with open('prompts/analysis-prompt.txt', encoding='utf-8') as f:
    PROMPT_TEMPLATE = f.read()

def get_prompt(image_count=NUM_IMAGES, target_lang='无文字(纯视觉)', reqs=FALLBACK_REQUIREMENTS):
    return PROMPT_TEMPLATE.replace('{IMAGE_COUNT}', str(image_count)).replace('{TARGET_LANGUAGE}', target_lang).replace('{REQUIREMENTS}', reqs)

def picset_headers():
    return {'Authorization': f'Bearer {ACCESS_TOKEN}', 'apikey': ANON_KEY, 'Content-Type': 'application/json'}

def upload_to_picset(img_path):
    creds = requests.post(f'{BASE}/functions/v1/get-oss-sts', headers=picset_headers(), json={}).json()
    if 'accessKeyId' not in creds:
        raise Exception(f'OSS STS failed: {creds}')
    auth = oss2.StsAuth(creds['accessKeyId'], creds['accessKeySecret'], creds['securityToken'])
    bucket = oss2.Bucket(auth, f'https://{creds["region"]}.aliyuncs.com', creds['bucket'])
    key = f'temp/{USER_ID}/{int(time.time()*1000)}_product_0.png'
    with open(img_path, 'rb') as f:
        bucket.put_object(key, f)
    return key

def picset_analyze(object_key, num_images=NUM_IMAGES):
    # PicSet still gets the old generic one-liner so the comparison stays apples-to-apples
    # (we test our pipeline's IMPROVEMENT vs PicSet, not PicSet's potential with better input)
    resp = requests.post(f'{BASE}/functions/v1/analyze-product-v2', headers=picset_headers(), json={
        'imageType': 'detail', 'imageCount': num_images, 'targetLanguage': 'none',
        'uiLanguage': 'zh-CN', 'productImage': object_key, 'productImages': [object_key],
        'requirements': FALLBACK_REQUIREMENTS, 'themeColors': None
    }, timeout=60)
    data = resp.json()
    job_id = data.get('job_id')
    if not job_id:
        return None
    for i in range(60):
        time.sleep(2)
        r = requests.get(f'{BASE}/rest/v1/generation_jobs?select=*&id=eq.{job_id}', headers=picset_headers())
        if r.status_code == 200 and r.json():
            job = r.json()[0]
            if job['status'] == 'success':
                return job['result_data']
            elif job['status'] == 'failed':
                return None
    return None

def our_analyze(img_path, num_images=NUM_IMAGES):
    # Step 0: auto-generate product-specific 详情图要求 from the photo
    requirements = analyze_product(img_path)
    print(f'  [Step 0] Generated requirements ({len(requirements)} chars)', flush=True)

    with open(img_path, 'rb') as f:
        ref = types.Part.from_bytes(data=f.read(), mime_type='image/jpeg')

    # Step 1: planning with the product-specific requirements
    prompt = get_prompt(num_images, reqs=requirements)
    resp = gemini.models.generate_content(
        model=PLANNING_MODEL,
        config=types.GenerateContentConfig(
            temperature=0.4, max_output_tokens=8192 if num_images <= 5 else 16384,
            response_mime_type='application/json',
        ),
        contents=[prompt, 'This is the product image:', ref],
    )
    plan = json.loads(resp.text)
    plan['_meta'] = {
        'generated_requirements': requirements,
        'planning_model': PLANNING_MODEL,
    }
    return plan

def generate_image(system_ctx, brief, ref_part, output_path):
    try:
        resp = gemini.models.generate_content(
            model=GENERATION_MODEL,
            config=types.GenerateContentConfig(
                response_modalities=['IMAGE'],
                system_instruction=system_ctx + "\n\n请根据以上参考照片中的真实产品，生成一张1:1正方形的电商产品场景图。必须严格还原产品的真实外观、结构和细节，不得添加或省略任何部件。",
                image_config=types.ImageConfig(image_size='2K', aspect_ratio='1:1'),
            ),
            contents=[ref_part, brief],
        )
        for part in resp.candidates[0].content.parts:
            if part.inline_data:
                with open(output_path, 'wb') as f:
                    f.write(part.inline_data.data)
                return True
    except Exception as e:
        print(f'    GEN ERR: {e}')
    return False

# score_image is now imported from evaluator.py (Vertex AI / Gemini Flash)
# Old Claude OAuth implementation removed.

# === MAIN ===
OUT_DIR = 'evals/comparison-v2'
os.makedirs(OUT_DIR, exist_ok=True)
PRODUCTS = [f'test-products/stationery/product-{i:02d}.jpg' for i in range(1, 11)]

all_scores = []

for idx, img_path in enumerate(PRODUCTS, 1):
    if not os.path.exists(img_path):
        print(f'[{idx}/10] SKIP')
        continue

    pname = f'product-{idx:02d}'
    d = f'{OUT_DIR}/{pname}'
    os.makedirs(d, exist_ok=True)

    print(f'\n[{idx}/10] {pname}', flush=True)

    with open(img_path, 'rb') as f:
        ref_part = types.Part.from_bytes(data=f.read(), mime_type='image/jpeg')

    # --- PicSet Analysis (8 images) ---
    picset_plan_path = f'{d}/picset-plan.json'
    if os.path.exists(picset_plan_path):
        with open(picset_plan_path, encoding='utf-8') as f:
            picset_rd = json.load(f)
        print(f'  PicSet: cached ({len(picset_rd["images"])} imgs)', flush=True)
    else:
        print(f'  PicSet: uploading+analyzing...', end=' ', flush=True)
        try:
            obj_key = upload_to_picset(img_path)
            picset_rd = picset_analyze(obj_key, NUM_IMAGES)
            if picset_rd:
                with open(picset_plan_path, 'w', encoding='utf-8') as f:
                    json.dump(picset_rd, f, ensure_ascii=False, indent=2)
                print(f'OK ({len(picset_rd["images"])} imgs)', flush=True)
            else:
                print('FAILED', flush=True)
                picset_rd = None
        except Exception as e:
            print(f'ERR: {e}', flush=True)
            picset_rd = None

    # --- Our Analysis (8 images, same prompt) ---
    our_plan_path = f'{d}/our-plan.json'
    if os.path.exists(our_plan_path):
        with open(our_plan_path, encoding='utf-8') as f:
            our_rd = json.load(f)
        print(f'  Ours: cached ({len(our_rd["images"])} imgs)', flush=True)
    else:
        print(f'  Ours: analyzing...', end=' ', flush=True)
        try:
            our_rd = our_analyze(img_path, NUM_IMAGES)
            with open(our_plan_path, 'w', encoding='utf-8') as f:
                json.dump(our_rd, f, ensure_ascii=False, indent=2)
            print(f'OK ({len(our_rd["images"])} imgs)', flush=True)
        except Exception as e:
            print(f'ERR: {e}', flush=True)
            our_rd = None

    # --- Generate 1st image from each (for scoring) ---
    for source, plan in [('picset', picset_rd), ('ours', our_rd)]:
        if not plan:
            continue
        imgs = plan['images'] if 'images' in plan else plan.get('images', [])
        specs = plan.get('design_specs', '')
        img_path_out = f'{d}/{source}-img-1.png'
        if os.path.exists(img_path_out):
            print(f'  {source} img-1: cached', flush=True)
            continue
        if imgs:
            print(f'  {source} img-1: generating...', end=' ', flush=True)
            ok = generate_image(specs, imgs[0]['design_content'], ref_part, img_path_out)
            print('OK' if ok else 'FAIL', flush=True)
            time.sleep(3)

    # --- Score both ---
    picset_img = f'{d}/picset-img-1.png'
    our_img = f'{d}/ours-img-1.png'
    ref = img_path

    product_scores = {'product': pname, 'picset': -1, 'ours': -1}
    
    if os.path.exists(picset_img):
        print(f'  Scoring PicSet...', end=' ', flush=True)
        ps = score_image(ref, picset_img)
        product_scores['picset'] = ps.get('final_score', -1)
        product_scores['picset_verdict'] = ps.get('verdict')
        product_scores['picset_critical'] = ps.get('critical_issue')
        product_scores['picset_full'] = ps
        print(f'{product_scores["picset"]} ({ps.get("verdict", "?")})', flush=True)
    
    if os.path.exists(our_img):
        print(f'  Scoring Ours...', end=' ', flush=True)
        os_ = score_image(ref, our_img)
        product_scores['ours'] = os_.get('final_score', -1)
        product_scores['ours_verdict'] = os_.get('verdict')
        product_scores['ours_critical'] = os_.get('critical_issue')
        product_scores['ours_full'] = os_
        print(f'{product_scores["ours"]} ({os_.get("verdict", "?")})', flush=True)

    all_scores.append(product_scores)

# === SUMMARY ===
with open(f'{OUT_DIR}/scores.json', 'w', encoding='utf-8') as f:
    json.dump(all_scores, f, ensure_ascii=False, indent=2)

print(f'\n{"Product":<12} {"PicSet":<8} {"Ours":<8} {"Winner"}')
print('-' * 40)
pt = ot = n = 0
pw = ow = ties = 0
for r in all_scores:
    p, o = r['picset'], r['ours']
    if p < 0 or o < 0:
        continue
    w = 'PicSet' if p > o else ('Ours' if o > p else 'Tie')
    if p > o: pw += 1
    elif o > p: ow += 1
    else: ties += 1
    print(f'{r["product"]:<12} {p:<8} {o:<8} {w}')
    pt += p; ot += o; n += 1
print('-' * 40)
if n:
    print(f'{"Average":<12} {pt/n:<8.1f} {ot/n:<8.1f}')
    print(f'Wins: PicSet={pw} Ours={ow} Tie={ties}')
